sonar.projectKey=utilForever_CubbyFlow
sonar.organization=utilforever-github
sonar.projectName=CubbyFlow
sonar.projectVersion=0.72

# =====================================================
#   Meta-data for the project
# =====================================================

sonar.links.homepage=https://github.com/utilForever/CubbyFlow
sonar.links.ci=https://travis-ci.org/utilForever/CubbyFlow
sonar.links.scm=https://github.com/utilForever/CubbyFlow
sonar.links.issue=https://github.com/utilForever/CubbyFlow/issues

# =====================================================
#   Properties that will be shared amongst all modules
# =====================================================

# SQ standard properties
sonar.sources=.github,Includes,Sources,Tests
sonar.exclusions=Sources/Core/Flatbuffers/generated/**

# Properties specific to the C/C++ analyzer:
sonar.cfamily.build-wrapper-output=bw-output
sonar.cfamily.gcov.reportsPath=build/Tests/UnitTests/CMakeFiles
