name: Document

on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    name: 🗎 Docs
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Installation
      run: |
        sudo apt-get update
        sudo apt-get -y install ps2eps texlive-latex-extra doxygen
    - name: Build
      run: |
        pushd Documents/doxygen
          doxygen Doxyfile
        popd
        mv ../../Doxygen/html ./build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: build
        clean: true
